/****************************************************************************

 Earth Orientation Parameter Read and Interpolation


 ET = TAI + 32.184 s
 TAI = UTC + (TAI-UTC)

 UT1 = UTC + (UT1UTC)

****************************************************************************/
#include "EOP.h"

#include <cmath>
#include <string>
#include <fstream>

#if (_MSVC_LANG >= 201703L) || (__cplusplus >= 201703L) // C++ 17
#include <filesystem>
namespace fs = std::filesystem;
#else
#define _SILENCE_EXPERIMENTAL_FILESYSTEM_DEPRECATION_WARNING
#define _SILENCE_EXPERIMENTAL_FILESYSTEM_DEPRECATION_WARNING
#include <experimental/filesystem>
namespace fs = std::experimental::filesystem::v1;
#endif
#include <regex>

#include "Constant.h"
#include "DateTimeZ.h"

class cEOP g_EOP;

cEOP::cEOP()
{
	m_pstEOP.clear();

	m_dfTRANS = g_dfHALFPI / 324000.0;

	m_bInit = false;

	m_nLastIndex = 0;
}

cEOP::~cEOP()
{
	m_pstEOP.clear();
}

/****************************************************************************************

  Read EOP parameters from a unified EOP data file and TAI-UTC difference from the given
  file

  szEOPFileName: unified EOP data file. This file is generated by the application
                 EOPUnify in c:\Projects\EOPUnify. Its default name should be
				 D:\EOSORDP\IERS_EOP\ComEOP.Dat.
  szTAImUTCFileName: the file contains the difference between UTC and TAI, its default
                     file name is D:\EOSORDP\IERS_EOP\tai-utc.dat

*****************************************************************************************/

bool cEOP::ReadModified( const char *szEOPFileName, const char *szTAImUTCFileName )
{
	if( m_bInit ) return true;	// the files have been read

	// check whether the file exists
	if (!fs::exists(szEOPFileName)) return false;
	if (!fs::exists(szTAImUTCFileName)) return false;

	m_bInit = false;

	if( !ReadTAIUTCData( szTAImUTCFileName ) )
	{
		return false;
	}

	m_nNumberEOP = 0;
	m_pstEOP.clear();

	EOPData tEOP;

	{
		std::string line, sub;

        std::ifstream in( szEOPFileName );
        if ( !in.is_open( ) )
        {
            return false;
        }

		while( getline( in, line ) )
		{
			sub = line.substr( 0, 12 );
			tEOP.dfJD = atof( sub.c_str() );

			sub = line.substr( 12, 11 );
			tEOP.dfMJD = atof( sub.c_str() );

			sub = line.substr( 23, 13 );
			tEOP.dfX = atof( sub.c_str() ) / 206264.8;

			sub = line.substr( 36, 13 );
			tEOP.dfY = atof( sub.c_str() ) / 206264.8;

			sub = line.substr( 49, 13 );
			tEOP.dfUT1UTC = atof( sub.c_str() );

			sub = line.substr( 75, 13 );
			tEOP.dfDPSI = atof( sub.c_str() ) / 206264.8;

			sub = line.substr( 88, 13 );
			tEOP.dfDEPS = atof( sub.c_str() ) / 206264.8;

			m_pstEOP.push_back( tEOP );
			m_nNumberEOP++;
		}

		m_bInit = true;
		m_nLastIndex = 0;

		return true;
	}
}

bool cEOP::Read( const char *szEOPFileName, const char *szTAImUTCFileName )
{
	if( m_bInit ) return true;	// the files have been read

	// check whether the file exists
	if (!fs::exists(szEOPFileName)) return false;
	if (!fs::exists(szTAImUTCFileName)) return false;

	m_bInit = false;

	if( !ReadTAIUTCData( szTAImUTCFileName ) )
	{
		return false;
	}

	/////////////////////////////////
	// read EOP file

	m_nNumberEOP = 0;
	m_pstEOP.clear();


	std::ifstream in( szEOPFileName );
	if ( !in.is_open( ) )
		return false;
	
	std::string line;

	/////////////////////////////////
	// Observed

	// get OBSERVED number
	int observed_num{0};
	while(std::getline(in, line))
	{
		auto pos = line.find("NUM_OBSERVED_POINTS");
		if (pos != std::string::npos)
		{
			observed_num = std::atoi(line.substr(pos + 20).c_str());
			break;
		}
	}

	if (observed_num == 0)
		return false;
	
	std::getline( in, line );
	if (line.find("BEGIN OBSERVED") == std::string::npos)
		return false;

	for (size_t i = 0; i < observed_num; i++)
	{
		EOPData eop;
		in >> eop;
		m_pstEOP.emplace_back(std::move(eop));
	}

	std::getline( in, line );
	if (line.find("END OBSERVED") == std::string::npos)
		return false;
	
	/////////////////////////////////
	// PREDICTED

	int predicted_num{0};
	while(std::getline(in, line))
	{
		auto pos = line.find("NUM_PREDICTED_POINTS");
		if (pos != std::string::npos)
		{
			predicted_num = std::atoi(line.substr(pos + 21).c_str());
			break;
		}
	}

	if (predicted_num == 0)
		return false;
	
	std::getline( in, line );
	if (line.find("BEGIN PREDICTED") == std::string::npos)
		return false;

	for (size_t i = 0; i < predicted_num; i++)
	{
		EOPData eop;
		in >> eop;
		m_pstEOP.emplace_back(std::move(eop));
	}

	std::getline( in, line );
	if (line.find("END PREDICTED") == std::string::npos)
		return false;

	m_nNumberEOP =  observed_num + predicted_num;

	m_bInit = true;
	m_nLastIndex = 0;

	return true;
}

/****************************************************************************************

  Compute the polar trans matrix at the given time.
  The trans matrix is from mean pole to true pole.

  Here, dfJD is regarded as UTC JD, the same as in the EOP data file. Because the
  differences between UTC, UT, TAI, ET are small enough to be neglected for the purpose
  of computing the polar motion matrix, dfJD could be in any one of the UTC, UT, TAL and
  ET time systems.

*****************************************************************************************/

bool cEOP::ComputePole( double dfJD, double *pdfPole )
{
	if( !m_bInit )
	{
		return false;
	}

	double x, y;

	if( !GetPolarMotion( dfJD, x, y, true ) )
	{
		return false;
	}

	pdfPole[ 0 ] = 1.0;
	pdfPole[ 3 ] = x * y;
	pdfPole[ 6 ] = x;
	pdfPole[ 1 ] = 0.0;
	pdfPole[ 4 ] = 1.0;
	pdfPole[ 7 ] = -y;
	pdfPole[ 2 ] = -x;
	pdfPole[ 5 ] = y;
	pdfPole[ 8 ] = 1.0;

	return true;
}

/****************************************************************************************

  Get the polar motion parameters at the given time

  dfJD: time in JD of interest
  dfX, dfY: obtained polar motion parameters in radians
  bJDUTC: true, then the given dfJD is in UTC, otherwise dfJD is in ET

*****************************************************************************************/

bool cEOP::GetPolarMotion( double dfJD, double &dfX, double &dfY, bool bJDUTC, bool bApplyDiurnalCorrection )
{
	if( !m_bInit )
	{
		return false;
	}

	int nIndex;
	double dfJDUTC;

	if( !GetIndex( dfJD, dfJDUTC, bJDUTC, nIndex ) )
	{
		return false;
	}

	dfX = dfY = 0;
	double dfTX, dfTY;

	for( int i = nIndex; i < nIndex + 4; i++ )
	{
		dfTX = m_pstEOP[ i ].dfX;
		dfTY = m_pstEOP[ i ].dfY;

		for( int j = nIndex; j < nIndex + 4; j++ )
		{
			if( i != j )
			{
				double dfT = ( dfJDUTC - m_pstEOP[ j ].dfJD ) /
					         ( m_pstEOP[ i ].dfJD - m_pstEOP[ j ].dfJD );

				dfTX *= dfT;
				dfTY *= dfT;
			}
		}

		dfX += dfTX;
		dfY += dfTY;
	}

	if( !bApplyDiurnalCorrection ) return true;

	// correct for diurnal and semi-diurnal tidal variation
	double eop[ 3 ];

	ComputeTidalVariation( dfJD, eop[ 0 ], eop[ 1 ], eop[ 2 ] );

	dfX += eop[ 0 ] / 206264.8;
	dfY += eop[ 1 ] / 206264.8;

	return true;
}

bool cEOP::GetPolarMotion( int nIndex, double &dfJD, double &dfX, double &dfY, bool bApplyDiurnalCorrection )
{
	if( !m_bInit )
	{
		return false;
	}

	if( nIndex < 0 || nIndex >= m_nNumberEOP )
	{
		return false;
	}

	dfJD = m_pstEOP[ nIndex ].dfJD;
	dfX = m_pstEOP[ nIndex ].dfX;
	dfY = m_pstEOP[ nIndex ].dfY;

	if( !bApplyDiurnalCorrection ) return true;

	// correct for diurnal and semi-diurnal tidal variation
	double eop[ 3 ];

	ComputeTidalVariation( dfJD, eop[ 0 ], eop[ 1 ], eop[ 2 ] );

	dfX += eop[ 0 ] / 206264.8;
	dfY += eop[ 1 ] / 206264.8;

	return true;
}

/****************************************************************************************

  Get the UT1-UTC parameter at the given epoch

  dfJD: time in JD of interest
  dfUT1UTC: obtained UT1-UTC parameters in seconds of time
  bJDUTC: true, then the given dfJD is in UTC, otherwise dfJD is in ET

  The leap second problem is treated. When a leap second is introduced, the UT1-UTC
  values will have a jump of 1 second. Because we use 4 UT1-UTC table values to determine
  the UT1-UTC at the epoch of interest, so the standatd deviation of the four table values
  (against their mean) is used to see whether there is a leap second within the four
  table values.

*****************************************************************************************/

bool cEOP::GetUT1UTC( double dfJD, double &dfUT1UTC, bool bJDUTC, bool bApplyDiurnalCorrection )
{
	dfUT1UTC = 0;
	if( !m_bInit )
	{
		return false;
	}

	int nIndex;
	double dfJDUTC;

	if( !GetIndexUT1UTC( dfJD, dfJDUTC, bJDUTC, nIndex ) )
	{
		return false;
	}

	int nIndex0 = nIndex;

	if( nIndex0 > 0 ) nIndex0--;

	double p[ 4 ], sum = 0;
	int k = 0, i;

	for( i = nIndex0; i < nIndex0 + 4; i++ )
	{
		p[ k ] = m_pstEOP[ i ].dfUT1UTC;
		sum += p[ k ];
		k++;
	}

	double mean = sum / 4.0;

	sum = 0;

	for( i = 0; i < 4; i++ ) sum += ( p[ i ] - mean ) * ( p[ i ] - mean );

	double std = sqrt( sum / 4.0 );

	if( std > 0.1 ) // there is a leap second
	{
		if( fabs( p[ 0 ] - p[ 1 ] ) > 0.1 )
		{
			if( fabs( p[ 1 ] - p[ 0 ] - 1.0 ) < 0.01 ) p[ 0 ] += 1.0;
			else if( fabs( p[ 1 ] - p[ 0 ] + 1.0 ) < 0.01 ) p[ 0 ] -= 1.0;
		}

		for( i = 2; i < 4; i++ )
		{
			if( fabs( p[ i ] - p[ 1 ] ) > 0.1 )
			{
				if( fabs( p[ i ] - p[ 1 ] - 1.0 ) < 0.01 ) p[ i ] -= 1.0;
				else if( fabs( p[ i ] - p[ 1 ] + 1.0 ) < 0.01 ) p[ i ] -= 1.0;
			}
		}
	}

	dfUT1UTC = 0;
	double dfTX;

	k = 0;

	for( i = nIndex0; i < nIndex0 + 4; i++ )
	{
		dfTX = p[ k ];

		for( int j = nIndex0; j < nIndex0 + 4; j++ )
		{
			if( i != j )
			{
				double dfT = ( dfJDUTC - m_pstEOP[ j ].dfJD ) /
					         ( m_pstEOP[ i ].dfJD - m_pstEOP[ j ].dfJD );

				dfTX *= dfT;
			}
		}

		dfUT1UTC += dfTX;
		k++;
	}

	if( !bApplyDiurnalCorrection ) return true;

	// correct for diurnal and semi-diurnal tidal variation
	double eop[ 3 ];

	ComputeTidalVariation( dfJD, eop[ 0 ], eop[ 1 ], eop[ 2 ] );

	dfUT1UTC += eop[ 2 ];

	return true;
}

/****************************************************************************************

  Get the TAI and UTC difference at given epoch

  dfJD: time in JD of interest
  dfTAIUTC: obtained TAI-UTC differece in seconds of time
  bJDUTC: true, then the given dfJD is in UTC, otherwise dfJD is in TAI

*****************************************************************************************/

bool cEOP::GetTAIUTC( double dfJD, double &dfTAIUTC, bool bJDUTC )
{
	if( !m_bInit )
	{
		return false;
	}

	if( bJDUTC )
	{
		if( dfJD < m_pstTAIUTC[ 0 ].dfJDUTC )
		{
			return false;
		}
	}
	else
	{
		if( dfJD < m_pstTAIUTC[ 0 ].dfJDTAI )
		{
			return false;
		}
	}


	int nIndex = -1;

	for( int i = 0; i < m_nNumberTAIUTC - 1; i++ )
	{
		if( bJDUTC )
		{
			if( dfJD >= m_pstTAIUTC[ i ].dfJDUTC &&
				dfJD < m_pstTAIUTC[ i + 1 ].dfJDUTC )
			{
				nIndex = i;
				break;
			}
		}
		else
		{
			if( dfJD >= m_pstTAIUTC[ i ].dfJDTAI &&
				dfJD < m_pstTAIUTC[ i + 1 ].dfJDTAI )
			{
				nIndex = i;
				break;
			}
		}
	}

	if( nIndex == -1 ) nIndex = m_nNumberTAIUTC - 1;

	double dfJDUTC = dfJD;

	if( !bJDUTC ) dfJDUTC = dfJD - m_pstTAIUTC[ nIndex ].df0 / 86400.0;

	dfTAIUTC = m_pstTAIUTC[ nIndex ].df0 +
		       m_pstTAIUTC[ nIndex ].df1 *
			   ( dfJDUTC - g_dfMJDRef - m_pstTAIUTC[ nIndex ].dfMJD );

	return true;
}


/****************************************************************************************

  Get the Delta PSI and EPS at the given epoch

  dfJD: time in JD of interest
  dfDPSI, dfDEPS: obtained Delta PSI and EPS in radians
  bJDUTC: true, then the given dfJD is in UTC, otherwise dfJD is in ET

*****************************************************************************************/

bool cEOP::GetDPSIDEPS( double dfJD, double &dfDPSI, double &dfDEPS, bool bJDUTC )
{
	if( !m_bInit )
	{
		return false;
	}

	int nIndex;
	double dfJDUTC;

	if( !GetIndex( dfJD, dfJDUTC, bJDUTC, nIndex ) )
	{
		return false;
	}

	dfDPSI = dfDEPS = 0;
	double dfTX, dfTY;

	for( int i = nIndex; i < nIndex + 4; i++ )
	{
		dfTX = m_pstEOP[ i ].dfDPSI;
		dfTY = m_pstEOP[ i ].dfDEPS;

		for( int j = nIndex; j < nIndex + 4; j++ )
		{
			if( i != j )
			{
				double dfT = ( dfJDUTC - m_pstEOP[ j ].dfJD ) /
					         ( m_pstEOP[ i ].dfJD - m_pstEOP[ j ].dfJD );

				dfTX *= dfT;
				dfTY *= dfT;
			}
		}

		dfDPSI += dfTX;
		dfDEPS += dfTY;
	}

	return true;
}


/****************************************************************************************

  Get the polar motion parameters and UT1-UTC at the given epoch

  dfJD: time in JD of interest
  dfX, dfY: obtained polar motion parameters in radians
  dfUT1UTC: obtained Ut1-UTC parameters in seconds of time
  bJDUTC: true, then the given dfJD is in UTC, otherwise dfJD is in ET

*****************************************************************************************/

bool cEOP::GetPolarMotionUT1UTC( double dfJD, double &dfX, double &dfY,
								 double &dfUT1UTC, bool bJDUTC, bool bApplyDiurnalCorrection )
{
	if( !m_bInit )
	{
		return false;
	}

	if( !GetPolarMotion( dfJD, dfX, dfY, bJDUTC, bApplyDiurnalCorrection ) )
	{
		return false;
	}

	if( !GetUT1UTC( dfJD, dfUT1UTC, bJDUTC, bApplyDiurnalCorrection ) )
	{
		return false;
	}

	return true;
}

bool cEOP::GetDateRange(double &jd_start, double &jd_end)
{
	if(m_pstEOP.size() < 1)
		return false;

	jd_start = m_pstEOP.front().dfJD;
	jd_end = m_pstEOP.back().dfJD;

	return true;
}

double cEOP::GetDateStart()
{
	if(m_pstEOP.size() < 1)
		return 0;
	
	return m_pstEOP.front().dfJD;
}

double cEOP::GetDateEnd()
{
	if(m_pstEOP.size() < 1)
		return 0;
	
	return m_pstEOP.back().dfJD;
}


/****************************************************************************************
  FORTRAN Subroutine RAY

  THIS SUBROUTINE IMPLEMENTS THE RAY MODEL FOR DIURNAL/SUBDIURNAL TIDES.
  IT USES THE SIMON ET AL. FUNDAMENTAL ARGUMENTS. THE CORRECTIONS IN X AND Y ARE
  IN UNITS OF SEC. OF ARC AND UT1-UTC IN SEC. OF TIME. THESE CORRECTIONS SHOULD BE
  ADDED TO "AVERAGE" EOP VALUES TO GET ESTIMATES OF THE INSTANTANEOUS VALUES.

  dfJD: time in JD of interest
  dfDeltaX, dfDeltaY: computed delta polar motion parameters in arc sec
  dfDeltaUT1UTC: computed delta UT1-UTC difference in second of time

  nSwitch - 1 ONLY DeltaX AND DeltaY ARE COMPUTED
            2 ONLY DeltaUT1UTC IS COMPUTED
            3 ALL ARE COMPUTED

*****************************************************************************************/

bool cEOP::RayModel( double dfJD, double &dfDeltaX, double &dfDeltaY,
					 double &dfDeltaUT1UTC, int nSwitch )
{
	{
		double dfT = ( dfJD - g_dfJ2000 ) / 36525.0,
			dfT2 = dfT * dfT,
			dfT3 = dfT2 * dfT,
			dfT4 = dfT3 * dfT;

		double dfL = -0.00024470 * dfT4 + 0.051635 * dfT3 + 31.8792 * dfT2 +
					1717915923.2178 * dfT + 485868.249036;
		dfL = fmod( dfL, 1296000.0 );	//	in arc sec

		double dfLPRIME = -0.00001149 * dfT4 - 0.000136 * dfT3 - 0.5532 * dfT2 +
						129596581.0481 * dfT + 1287104.79305;
		dfLPRIME = fmod( dfLPRIME, 1296000.0 );

		double dfF = 0.00000417 * dfT4 - 0.001037 * dfT3 - 12.7512 * dfT2 +
					1739527262.8478 * dfT + 335779.526232;
		dfF = fmod( dfF, 1296000.0 );

		double dfD = -0.00003169 * dfT4 + 0.006593 * dfT3 - 6.3706 * dfT2 +
			1602961601.2090 * dfT + 1072260.70369;

		dfD = fmod( dfD, 1296000.0 );

		double dfOMEGA = -0.00005939 * dfT4 + 0.007702 *dfT3 + 7.4722 * dfT2 -
						6962890.2665 * dfT + 450160.398036;
		dfOMEGA = fmod( dfOMEGA, 1296000.0 );

		double dfTHETA =
			( 67310.54841 +
			( 876600.0 * 3600.0 + 8640184.812866 ) * dfT +
				0.093104 * dfT2 - 6.2e-6 * dfT3                ) * 15.0 +
			648000.0;

		double dfARG7 =
			fmod( ( -dfL - 2.0 * dfF - 2.0 * dfOMEGA + dfTHETA ) * m_dfTRANS,
				g_dfTWOPI ) - g_dfHALFPI;
		double dfARG1 =
			fmod( ( -2.0 * dfF - 2.0 * dfOMEGA + dfTHETA ) * m_dfTRANS,
				g_dfTWOPI ) - g_dfHALFPI;
		double dfARG2 =
			fmod( ( -2.0 * dfF + 2.0 * dfD - 2.0 * dfOMEGA + dfTHETA ) * m_dfTRANS,
				g_dfTWOPI ) - g_dfHALFPI;
		double dfARG3 = fmod( dfTHETA * m_dfTRANS, g_dfTWOPI ) + g_dfHALFPI;
		double dfARG4 =
			fmod( ( -dfL - 2.0 * dfF - 2.0 * dfOMEGA + 2.0 * dfTHETA ) * m_dfTRANS,
				g_dfTWOPI );
		double dfARG5 =
			fmod( ( -2.0 * dfF - 2.0 * dfOMEGA + 2.0 * dfTHETA ) * m_dfTRANS,
				g_dfTWOPI );
		double dfARG6 =
			fmod( ( -2.0 * dfF + 2.0 * dfD - 2.0 * dfOMEGA + 2.0 * dfTHETA ) * m_dfTRANS,
				g_dfTWOPI );
		double dfARG8 = fmod( ( 2.0 * dfTHETA ) * m_dfTRANS, g_dfTWOPI );

		double dfSinARG7 = sin( dfARG7 ), dfCosARG7 = cos( dfARG7 );
		double dfSinARG1 = sin( dfARG1 ), dfCosARG1 = cos( dfARG1 );
		double dfSinARG2 = sin( dfARG2 ), dfCosARG2 = cos( dfARG2 );
		double dfSinARG3 = sin( dfARG3 ), dfCosARG3 = cos( dfARG3 );
		double dfSinARG4 = sin( dfARG4 ), dfCosARG4 = cos( dfARG4 );
		double dfSinARG5 = sin( dfARG5 ), dfCosARG5 = cos( dfARG5 );
		double dfSinARG6 = sin( dfARG6 ), dfCosARG6 = cos( dfARG6 );
		double dfSinARG8 = sin( dfARG8 ), dfCosARG8 = cos( dfARG8 );

		if( nSwitch == 1 || nSwitch == 3 )
		{
			dfDeltaX = - 0.026 * dfSinARG7 + 0.006 * dfCosARG7
					- 0.133 * dfSinARG1 + 0.049 * dfCosARG1
					- 0.050 * dfSinARG2 + 0.025 * dfCosARG2
					- 0.152 * dfSinARG3 + 0.078 * dfCosARG3
					- 0.057 * dfSinARG4 - 0.013 * dfCosARG4
					- 0.330 * dfSinARG5 - 0.028 * dfCosARG5
					- 0.145 * dfSinARG6 + 0.064 * dfCosARG6
					- 0.036 * dfSinARG8 + 0.017 * dfCosARG8;

			dfDeltaY = - 0.006 * dfSinARG7 - 0.026 * dfCosARG7
					- 0.049 * dfSinARG1 - 0.133 * dfCosARG1
					- 0.025 * dfSinARG2 - 0.050 * dfCosARG2
					- 0.078 * dfSinARG3 - 0.152 * dfCosARG3
					+ 0.011 * dfSinARG4 + 0.033 * dfCosARG4
					+ 0.037 * dfSinARG5 + 0.196 * dfCosARG5
					+ 0.059 * dfSinARG6 + 0.087 * dfCosARG6
					+ 0.018 * dfSinARG8 + 0.022 * dfCosARG8;

			dfDeltaX *= 1.0e-3;	//IN ARC SEC
			dfDeltaY *= 1.0e-3;	//IN ARC SEC
		}

		if( nSwitch == 2 || nSwitch == 3 )
		{
			dfDeltaUT1UTC = + 0.0245 * dfSinARG7 + 0.0503 * dfCosARG7
							+ 0.1210 * dfSinARG1 + 0.1605 * dfCosARG1
							+ 0.0286 * dfSinARG2 + 0.0516 * dfCosARG2
							+ 0.0864 * dfSinARG3 + 0.1771 * dfCosARG3
							- 0.0380 * dfSinARG4 - 0.0154 * dfCosARG4
							- 0.1617 * dfSinARG5 - 0.0720 * dfCosARG5
							- 0.0759 * dfSinARG6 - 0.0004 * dfCosARG6
							- 0.0196 * dfSinARG8 - 0.0038 * dfCosARG8;

			dfDeltaUT1UTC *= 1.0e-3;	// in sec of time
		}

		return true;
	}
}

/****************************************************************************************

  Conversion between UTC and UT seconds

*****************************************************************************************/

bool cEOP::ConvertUTCUT( double &dfIntSecUTC, double &dfFractionSecUTC,
				         double &dfIntSecUT, double &dfFractionSecUT, bool bUTC2UT )
{
	double dfJD, dfUT1UTC;

	if( bUTC2UT )	// from UTC to UT
	{
		g_DateTimeZ.ConversionJDSecond( dfJD, dfIntSecUTC, dfFractionSecUTC, false );

		if( !GetUT1UTC( dfJD, dfUT1UTC, true ) )
		{
			return false;
		}

		dfIntSecUT = dfIntSecUTC;
		dfFractionSecUT = dfFractionSecUTC + dfUT1UTC;
		g_DateTimeZ.ReConstruct( dfIntSecUT, dfFractionSecUT );
	}
	else	// from UT to UTC
	{
		g_DateTimeZ.ConversionJDSecond( dfJD, dfIntSecUT, dfFractionSecUT, false );

		if( !GetUT1UTC( dfJD, dfUT1UTC, true ) )
		{
			return false;
		}

		dfIntSecUTC = dfIntSecUT;
		dfFractionSecUTC = dfFractionSecUT - dfUT1UTC;
		g_DateTimeZ.ReConstruct( dfIntSecUTC, dfFractionSecUTC );
	}

	return true;
}


bool cEOP::ConvertUTCUT( double &dfJDUTC, double &dfJDUT, bool bUTC2UT )
{
	double dfUT1UTC;

	if( bUTC2UT )	// from UTC to UT
	{
		if( !GetUT1UTC( dfJDUTC, dfUT1UTC, true ) )
		{
			return false;
		}

        dfJDUT = dfJDUTC + dfUT1UTC / 86400.0;
	}
	else	// from UT to UTC
	{
		if( !GetUT1UTC( dfJDUT, dfUT1UTC, true ) )
		{
			return false;
		}

        dfJDUTC = dfJDUT - dfUT1UTC / 86400.0;
	}

	return true;
}

/****************************************************************************************

  Fortran Subroutine: convert_et_to_ut

  Conversion between ET and UTC

  dfJDET: either input or output of ET time in JD
  dfJDUT: either input or output of UT time in JD
  bET2UT = true then convert from ET 2 UT, vice versa

*****************************************************************************************/

bool cEOP::ConvertETUT( double &dfJDET, double &dfJDUT, bool bET2UT )
{
	if( !m_bInit )
	{
		return false;
	}

	double dfJDUTC;
	double dfUT1UTC;	// in seconds

	if( bET2UT )	// from ET (or TT) to UT
	{
		if( !ConvertETUTC( dfJDET, dfJDUTC, true ) )
		{
			return false;
		}

		if( !GetUT1UTC( dfJDUTC, dfUT1UTC, true ) )
		{
			return false;
		}

		dfJDUT = dfJDUTC + dfUT1UTC / 86400.0;
	}
	else	// from UT to ET
	{
		if( !GetUT1UTC( dfJDUT, dfUT1UTC, true ) )
		{
			return false;
		}

		dfJDUTC = dfJDUT - dfUT1UTC / 86400.0;

		if( !ConvertETUTC( dfJDET, dfJDUTC, false ) )
		{
			return false;
		}
	}

	return true;
}

/***************************************************************************************

 conversion of JD between ET and UT1

***************************************************************************************/

bool cEOP::ConvertJDETUT( double &dfIntJDET, double &dfFraJDET,
						  double &dfIntJDUT, double &dfFraJDUT, bool bET2UT )
{
	double dfIntSecET, dfFraSecET, dfIntSecUT, dfFraSecUT;

	if( bET2UT ) // from ET to UT
	{
		g_DateTimeZ.ConversionJDSecond
			( dfIntJDET, dfFraJDET, dfIntSecET, dfFraSecET, true );

		if( !ConvertETUT( dfIntSecET, dfFraSecET, dfIntSecUT, dfFraSecUT, true ) )
		{
			return false;
		}

		g_DateTimeZ.ConversionJDSecond
			( dfIntJDUT, dfFraJDUT, dfIntSecUT, dfFraSecUT, false );
	}
	else // from UT to ET
	{
		g_DateTimeZ.ConversionJDSecond
			( dfIntJDUT, dfFraJDUT, dfIntSecUT, dfFraSecUT, true );

		if( !ConvertETUT( dfIntSecET, dfFraSecET, dfIntSecUT, dfFraSecUT, false ) )
		{
			return false;
		}

		g_DateTimeZ.ConversionJDSecond
			( dfIntJDET, dfFraJDET, dfIntSecET, dfFraSecET, false );
	}

	return true;
}

/****************************************************************************************

  Fortran Subroutine: convert_et_to_ut

  Conversion between ET and UT

  dfIntSecET, dfFractionSecET: either input or output of ET time in seconds
  dfIntSecUT, dfFractionSecUT: either input or output of UT time in seconds

  bET2UT = true then convert from ET 2 UT, vice versa

*****************************************************************************************/

bool cEOP::ConvertETUT( double &dfIntSecET, double &dfFractionSecET,
						double &dfIntSecUT, double &dfFractionSecUT, bool bET2UT )
{
	if( !m_bInit )
	{
		return false;
	}

	double dfIntSecUTC, dfFractionSecUTC;
	double dfUT1UTC;
	double dfJDUT;

	double dfJDUTC;

	if( bET2UT )	// from ET (or TT) to UT
	{
		if( !ConvertETUTC( dfIntSecET, dfFractionSecET,
			               dfIntSecUTC, dfFractionSecUTC, true ) )
		{
			return false;
		}

		g_DateTimeZ.ConversionJDSecond
			( dfJDUTC, dfIntSecUTC, dfFractionSecUTC, false );

		if( !GetUT1UTC( dfJDUTC, dfUT1UTC, true ) )
		{
			return false;
		}

		dfIntSecUT = dfIntSecUTC;
		dfFractionSecUT = dfFractionSecUTC + dfUT1UTC;
		g_DateTimeZ.ReConstruct( dfIntSecUT, dfFractionSecUT );
	}
	else	// from UT to ET
	{
		g_DateTimeZ.ConversionJDSecond
			( dfJDUT, dfIntSecUT, dfFractionSecUT, false );

		if( !GetUT1UTC( dfJDUT, dfUT1UTC, true ) )
		{
			return false;
		}

		dfIntSecUTC = dfIntSecUT;
		dfFractionSecUTC = dfFractionSecUT - dfUT1UTC;

		if( !ConvertETUTC( dfIntSecET, dfFractionSecET,
			               dfIntSecUTC, dfFractionSecUTC, false ) )
		{
			return false;
		}
	}

	return true;
}


/****************************************************************************************

  Fortran Subroutine: convert_between_UTC_and_ET_single_point

  Conversion between ET and UTC

  dfJDET: either input or output of ET time in JD
  dfJDUTC: either input or output of UTC time in JD
  bET2UTC = true then convert from ET 2 UTC, vice versa

*****************************************************************************************/

bool cEOP::ConvertETUTC( double &dfJDET, double &dfJDUTC, bool bET2UTC )
{
	if( !m_bInit )
	{
		return false;
	}

	double dfJDTAI;
	double dfTAIUTC;

	if( bET2UTC )	// from ET (or TT) to UTC
	{
		dfJDTAI = dfJDET - g_dfTTmTAIInJD;

		if( !GetTAIUTC( dfJDTAI, dfTAIUTC, false ) )
		{
			return false;
		}

		dfJDUTC = dfJDTAI - dfTAIUTC / 86400.0;
	}
	else	// from UTC to ET
	{
		if( !GetTAIUTC( dfJDUTC, dfTAIUTC, true ) )
		{
			return false;
		}

		dfJDTAI = dfJDUTC + dfTAIUTC / 86400.0;
		dfJDET = dfJDTAI + g_dfTTmTAIInJD;
	}

	return true;
}

/****************************************************************************************

  Fortran Subroutine: convert_between_UTC_and_ET_single_point

  Conversion between ET and UTC

  dfIntSecET, dfFractionSecET: either input or output of ET time in seconds
  dfIntSecUTC, dfFractionSecUTC: either input or output of UTC time in seconds

  bET2UTC = true then convert from ET 2 UTC, vice versa

*****************************************************************************************/

bool cEOP::ConvertETUTC( double &dfIntSecET, double &dfFractionSecET,
						 double &dfIntSecUTC, double &dfFractionSecUTC, bool bET2UTC )
{
	if( !m_bInit )
	{
		return false;
	}

	double dfJDUTC, dfJDET;
	double dfTAIUTC;	// in sec

	if( bET2UTC )	// from ET (or TT) to UTC
	{
		g_DateTimeZ.ConversionJDSecond( dfJDET, dfIntSecET, dfFractionSecET, false );
		dfIntSecUTC = dfIntSecET;
		dfFractionSecUTC = dfFractionSecET - g_dfTTmTAIInSec;

		double dfJDTAI = dfJDET - g_dfTTmTAIInSec / 86400.0;

		if( !GetTAIUTC( dfJDTAI, dfTAIUTC, false ) )
		{
			return false;
		}

		dfFractionSecUTC -= dfTAIUTC;
		g_DateTimeZ.ReConstruct( dfIntSecUTC, dfFractionSecUTC );
	}
	else	// from UTC to ET
	{
		g_DateTimeZ.ConversionJDSecond( dfJDUTC, dfIntSecUTC, dfFractionSecUTC, false );

		if( !GetTAIUTC( dfJDUTC, dfTAIUTC, true ) )
		{
			return false;
		}

		dfIntSecET = dfIntSecUTC;
		dfFractionSecET = dfFractionSecUTC + dfTAIUTC;
		dfFractionSecET += g_dfTTmTAIInSec;
		g_DateTimeZ.ReConstruct( dfIntSecET, dfFractionSecET );
	}

	return true;
}


/****************************************************************************************

  Read TAI - UTC differences from a given file

  szTAImUTCFile: the file contains the difference between UTC and TAI, its default
                 file name is D:\EOSORDP\IERS_EOP\tai-utc.dat

*****************************************************************************************/

bool cEOP::ReadTAIUTCData( const char *szTAImUTCFile )
{
	{
		std::string line, sub;
		std::ifstream in( szTAImUTCFile );

		m_nNumberTAIUTC = 0;

		while( getline( in, line ) )
		{
			sub = line.substr( 16, 11 );
			m_pstTAIUTC[ m_nNumberTAIUTC ].dfJDUTC = atof( sub.c_str() );

			sub = line.substr( 36, 12 );
			m_pstTAIUTC[ m_nNumberTAIUTC ].df0 = atof( sub.c_str() );
			m_pstTAIUTC[ m_nNumberTAIUTC ].dfJDTAI = m_pstTAIUTC[ m_nNumberTAIUTC ].dfJDUTC + m_pstTAIUTC[ m_nNumberTAIUTC ].df0 / 86400.0;

			sub = line.substr( 59, 7 );
			m_pstTAIUTC[ m_nNumberTAIUTC ].dfMJD = atof( sub.c_str() );

			sub = line.substr( 69, 10 );
			m_pstTAIUTC[ m_nNumberTAIUTC ].df1 = atof( sub.c_str() );

			m_nNumberTAIUTC++;
		}

		return true;
	}
}

/****************************************************************************************

  Determine the index corresponding to the given time

  dfJD: time in JD of interest
  dfJDUTC: UTC time in JD of interest
  bJDUTC: true, then the given dfJD is in UTC, otherwise dfJD is in ET

  nIndex: determined index

*****************************************************************************************/

bool cEOP::GetIndex( double dfJD, double &dfJDUTC, bool bJDUTC, int &nIndex )
{
	if( !m_bInit )
	{
		return false;
	}

	dfJDUTC = dfJD;

	if( !bJDUTC ) ConvertETUTC( dfJD, dfJDUTC, true );

	nIndex = -1;

	int nStart = m_nLastIndex - 1500;
	nStart = max( nStart, 0 );

	for( int i = nStart; i < m_nNumberEOP - 1; i++ )
	{
		if( dfJDUTC >= m_pstEOP[ i ].dfJD && dfJDUTC < m_pstEOP[ i + 1 ].dfJD )
		{
			nIndex = i;
			break;
		}
	}

	if( nIndex == -1 ) return false;

	if( nIndex > 0 ) nIndex--;
	if( m_nNumberEOP - nIndex < 4 ) nIndex = m_nNumberEOP - 4;

	m_nLastIndex = nIndex;

	return true;
}

/****************************************************************************************

  Determine the index corresponding to the given time for UT1UTC

  dfJD: time in JD of interest
  dfJDUTC: UTC time in JD of interest
  bJDUTC: true, then the given dfJD is in UTC, otherwise dfJD is in ET

  nIndex: determined index

*****************************************************************************************/

bool cEOP::GetIndexUT1UTC( double dfJD, double &dfJDUTC, bool bJDUTC, int &nIndex )
{
	if( !m_bInit )
	{
		return false;
	}


	dfJDUTC = dfJD;

	if( !bJDUTC ) ConvertETUTC( dfJD, dfJDUTC, true );

	nIndex = -1;

	if( m_nLastIndex > m_nNumberEOP ) m_nLastIndex = 0;

	int nStart = m_nLastIndex - 1500;
	nStart = max( nStart, 0 );

	for( int i = nStart; i < m_nNumberEOP - 1; i++ )
	{
		if( dfJDUTC >= m_pstEOP[ i ].dfJD && dfJDUTC < m_pstEOP[ i + 1 ].dfJD )
		{
			nIndex = i;
			break;
		}
	}

	if( nIndex == -1 ) return false;

	m_nLastIndex = nIndex;

	return true;
}


/******************************************************************************

 delta_x. delta_y, output in arc sec
 delta_UT1 in seconds

******************************************************************************/

bool cEOP::ComputeTidalVariation( double dfJD,
		                          double &delta_x, double &delta_y, double &delta_UT1 )
{
	RayModel( dfJD, delta_x, delta_y, delta_UT1, 3 );

//	delta_x = delta_y = delta_UT1 = 0.0;
	return true;

	// computation of delta_x, delta_y and delta_UT1 is very time-consuming.
	// inclusion of these terms is not necessary at this stage for debris
	// orbit determination

	double dfMJD = dfJD - g_dfMJDRef, eop[ 3 ];

	Ortho_EOP( dfMJD, eop );

	delta_x = eop[ 0 ];
	delta_y = eop[ 1 ];
	delta_UT1 = eop[ 2 ];

	return false;
}


/******************************************************************************

  The following two methods are translated from fortran code ortho_eop.f of
  IERS Conventions 2000

******************************************************************************/


/******************************************************************************

   subroutines to compute the diurnal and semidiurnal variations
   in the earth orientation from the version of Richard Ray's ocean
   tide model that was listed in IERS Technical Note 21, July 1996.
   This code includes the variations from 71 diurnal and semidiurnal
   terms instead of the 8 that are listed in the report.

   dfMJD: modified julian date

   eop = (delta_x, delta_y, delta_UT1) in arc sec and seconds

   Original Fortran Code: Richard Eanes, UT/CSR, Feb 1997

******************************************************************************/

bool cEOP::Ortho_EOP( double dfMJD, double *eop )
{

//	diurnal and semidiurnal orthoweights fit to the 8 constituents
//	listed in IERS Technical Note 21, July 1996 which are from the
//	paper "Diurnal and Semidiurnal Variations in the Earth's Rotation
//	Rate Induced by Ocean Tides"  by Ray,R.D., Steinberg,D.J.,
//	Chao,B.F., and Cartwright, D.E., Science, 264, pp. 830-832.
	double orthow[ 12 * 3 ] =
	{
      -6.77832, -14.86323,  0.47884, -1.45303,  0.16406,  0.42030,
       0.09398,  25.73054, -4.77974,  0.28080,  1.94539, -0.73089,
      14.86283,  -6.77846,  1.45234,  0.47888, -0.42056,  0.16469,
      15.30276,  -4.30615,  0.07564,  2.28321, -0.45717, -1.62010,
      -1.76335,   1.03364, -0.27553,  0.34569, -0.12343, -0.10146,
	  -0.47119,   1.28997, -0.19336,  0.02724,  0.08955,  0.04726  };

	double h[ 12 ];

//	compute the partials of the tidal variations to the orthoweights
	ComputePartialsTidalVarWRTOrthoweight( dfMJD, h );

//	compute eop changes
	for( int k = 0; k < 3; k++ )
	{
		eop[ k ] = 0.0;

		for( int j = 0; j < 12; j++ )
		{
            eop[ k ] += h[ j ] * orthow[ j * 3 + k ];
		}
	}

	// delta_xp, delta_yp and delta_UT1 are in microarcsecs and microseconds,
	// so change the unit into arc sec and second

	eop[ 0 ] *= 1.0e-6;
	eop[ 1 ] *= 1.0e-6;
	eop[ 2 ] *= 1.0e-6;

	return true;
}

/******************************************************************************
	To compute the time dependent part of the second degree
    diurnal and semidiurnal tidal potential from the dominant
    spectral lines in the Cartwright-Tayler-Edden harmonic
    decomposition

	Original Fortran code: Richard Eanes, UT/CSR, Feb 1997
                           subroutine cnmtx (dmjd, h)

	dfMJD: modified julian date of the epoch of interest

	h: vector of length 12 with partials of the tidal
       variation with respect to the orthoweights

******************************************************************************/

bool cEOP::ComputePartialsTidalVarWRTOrthoweight( double dfMJD, double *h )
{
//	the orthotide weight factors
	struct sstt2
	{
		double f[ 2 ];
	};

    sstt2 sp[ 6 ], p[ 3 ], q[ 3 ];

	sp[ 0 ].f[ 0 ] = 0.0298;
	sp[ 1 ].f[ 0 ] = 0.1408;
	sp[ 2 ].f[ 0 ] = 0.0805;
	sp[ 3 ].f[ 0 ] = 0.6002;
	sp[ 4 ].f[ 0 ] = 0.3025;
	sp[ 5 ].f[ 0 ] = 0.1517;
	sp[ 0 ].f[ 1 ] = 0.0200;
	sp[ 1 ].f[ 1 ] = 0.0905;
	sp[ 2 ].f[ 1 ] = 0.0638;
	sp[ 3 ].f[ 1 ] = 0.3476;
	sp[ 4 ].f[ 1 ] = 0.1645;
	sp[ 5 ].f[ 1 ] = 0.0923;

	double dt  = 2.;
    int nmax = 2;

//	tidal potential model for 71 diurnal and semidiurnal lines

	double d1960 = 37076.5;

	// degree
	int nj[ 71 ], i;
	for( i = 0; i < 71; i++ ) nj[ i ] = 2;

	// orders
	int mj[ 71 ];
	for( i = 0; i < 41; i++ ) mj[ i ] = 1;
	for( i = 41; i < 71; i++ ) mj[ i ] = 2;

	// magnitude
	double hs[ 71 ] =
	{
		-1.94,  -1.25,  -6.64,  -1.51,  -8.02,  -9.47, -50.20,  -1.80,  -9.54,   1.52,
       -49.45,-262.21,   1.70,   3.43,   1.94,   1.37,   7.41,  20.62,   4.14,   3.94,
	    -7.14,   1.37,-122.03,   1.02,   2.89,  -7.30, 368.78,  50.01,  -1.08,   2.93,
		 5.25,   3.95,  20.62,   4.09,   3.42,   1.69,  11.29,   7.23,   1.52,   2.16,
		 1.38,   1.80,   4.67,  16.01,  19.32,   1.30,  -1.02,  -4.51, 120.99,   1.13,
        22.98,   1.06,  -1.90,  -2.18, -23.58, 631.92,   1.92,  -4.66, -17.86,   4.47,
		 1.97,  17.20, 294.00,  -2.46,  -1.02,  79.96,  23.83,   2.59,   4.47,   1.95,
		 1.17	};

	// phase
	double phase[ 71 ] =
	{
		9.0899831,  8.8234208, 12.1189598,  1.4425700,  4.7381090,
        4.4715466,  7.7670857, -2.9093042,  0.3862349, -3.1758666,
		0.1196725,  3.4152116, 12.8946194,  5.5137686,  6.4441883,
       -4.2322016, -0.9366625,  8.5427453, 11.8382843,  1.1618945,
	    5.9693878, -1.2032249,  2.0923141, -1.7847596,  8.0679449,
		0.8953321,  4.1908712,  7.4864102, 10.7819493,  0.3137975,
		6.2894282,  7.2198478, -0.1610030,  3.1345361,  2.8679737,
       -4.5128771,  4.9665307,  8.2620698, 11.5576089,  0.6146566,
	    3.9101957, 20.6617051, 13.2808543, 16.3098310,  8.9289802,
		5.0519065, 15.8350306,  8.6624178, 11.9579569,  8.0808832,
		4.5771061,  0.7000324, 14.9869335, 11.4831564,  4.3105437,
		7.6060827,  3.7290090, 10.6350594,  3.2542086, 12.7336164,
       16.0291555, 10.1602590,  6.2831853,  2.4061116,  5.0862033,
	    8.3817423, 11.6772814, 14.9728205,  4.0298682,  7.3254073,
		9.1574109	};

	// frequency
	double freq[ 71 ] =
	{
		5.18688050,  5.38346657,  5.38439079,  5.41398343,  5.41490765,
        5.61149372,  5.61241794,  5.64201057,  5.64293479,  5.83859664,
		5.83952086,  5.84044508,  5.84433381,  5.87485066,  6.03795537,
		6.06754801,  6.06847223,  6.07236095,  6.07328517,  6.10287781,
		6.24878055,  6.26505830,  6.26598252,  6.28318449,  6.28318613,
		6.29946388,  6.30038810,  6.30131232,  6.30223654,  6.31759007,
		6.33479368,  6.49789839,  6.52841524,  6.52933946,  6.72592553,
		6.75644239,  6.76033111,  6.76125533,  6.76217955,  6.98835826,
		6.98928248, 11.45675174, 11.48726860, 11.68477889, 11.71529575,
       11.73249771, 11.89560406, 11.91188181, 11.91280603, 11.93000800,
	   11.94332289, 11.96052486, 12.11031632, 12.12363121, 12.13990896,
	   12.14083318, 12.15803515, 12.33834347, 12.36886033, 12.37274905,
	   12.37367327, 12.54916865, 12.56637061, 12.58357257, 12.59985198,
	   12.60077620, 12.60170041, 12.60262463, 12.82880334, 12.82972756,
	   13.06071921	};

//	define anm[ 2:3, 0:3, -1:1] and bnm[ 2:3, 0:3, -1:1]
	struct st3
	{
		double f[ 3 ];	// for elements of last index [-1, 0, 1]
	};

	struct st2
	{
		st3 t3[ 4 ];
	};

	struct st1
	{
		st2 t2[ 2 ];

		void SetZero()
		{
			for( int i = 0; i < 2; i++ )
			{
				for( int j = 0; j < 4; j++ )
				{
					for( int k = 0; k < 3; k++ )
					{
						t2[ i ].t3[ j ].f[ k ] = 0.0;
					}
				}
			}
		}
	};

	st1 anm, bnm;

	anm.SetZero();
	bnm.SetZero();

	int j, k, m, n;

//	compute the time dependent potential matrix

	for( k = -1; k < 2; k++ )
	{
		double dt60 = ( dfMJD - k * dt ) - d1960;
		for( j = 0; j < 71; j++ )
		{
			n = nj[ j ];
            m = mj[ j ];
            double pinm = fmod( (double)( n + m ), 2.0 ) * g_dfHALFPI;
            double alpha = phase[ j ] + freq[ j ] * dt60 - pinm;
            alpha = fmod( alpha, g_dfTWOPI );
            anm.t2[ n - 1 ].t3[ m - 1 ].f[ k + 1 ] += hs[ j ]* cos( alpha );
            bnm.t2[ n - 1 ].t3[ m - 1 ].f[ k + 1 ] -= hs[ j ]* sin( alpha );
		}
	}

//	orthogonalize the response terms
	for( m = 0; m < 2; m++ )
	{
		double ap = anm.t2[ 1 ].t3[ m ].f[ 2 ] + anm.t2[ 1 ].t3[ m ].f[ 0 ];
		double am = anm.t2[ 1 ].t3[ m ].f[ 2 ] + anm.t2[ 1 ].t3[ m ].f[ 0 ];

		double bp = bnm.t2[ 1 ].t3[ m ].f[ 2 ] + bnm.t2[ 1 ].t3[ m ].f[ 0 ];
		double bm = bnm.t2[ 1 ].t3[ m ].f[ 2 ] + bnm.t2[ 1 ].t3[ m ].f[ 0 ];

        p[ 0 ].f[ m ] = sp[ 0 ].f[ m ] * anm.t2[ 1 ].t3[ m ].f[ 1 ];
        p[ 1 ].f[ m ] = sp[ 1 ].f[ m ] * anm.t2[ 1 ].t3[ m ].f[ 1 ] -
			            sp[ 2 ].f[ m ] * ap;
        p[ 2 ].f[ m ] = sp[ 3 ].f[ m ] * anm.t2[ 1 ].t3[ m ].f[ 1 ] -
			            sp[ 4 ].f[ m ] * ap + sp[ 5 ].f[ m ] * bm;

        q[ 0 ].f[ m ] = sp[ 0 ].f[ m ] * bnm.t2[ 1 ].t3[ m ].f[ 1 ];
        q[ 1 ].f[ m ] = sp[ 1 ].f[ m ] * bnm.t2[ 1 ].t3[ m ].f[ 1 ] -
			            sp[ 2 ].f[ m ] * bp;
        q[ 2 ].f[ m ] = sp[ 3 ].f[ m ] * bnm.t2[ 1 ].t3[ m ].f[ 1 ] -
			            sp[ 4 ].f[ m ] * bp - sp[ 5 ].f[ m ] * am;

		anm.t2[ 1 ].t3[ m ].f[ 0 ] = p[ 0 ].f[ m ];
		anm.t2[ 1 ].t3[ m ].f[ 1 ] = p[ 1 ].f[ m ];
		anm.t2[ 1 ].t3[ m ].f[ 2 ] = p[ 2 ].f[ m ];

		bnm.t2[ 1 ].t3[ m ].f[ 0 ] = q[ 0 ].f[ m ];
		bnm.t2[ 1 ].t3[ m ].f[ 1 ] = q[ 1 ].f[ m ];
		bnm.t2[ 1 ].t3[ m ].f[ 2 ] = q[ 2 ].f[ m ];
	}

//	fill partials vector
	j = 0;

	for( n = 1; n < nmax; n++ )
	{
		for( m = 0; m <= n; m++ )
		{
			for( k = 0; k < 3; k++ )
			{
				h[ j ]     = anm.t2[ n ].t3[ m ].f[ k ];
				h[ j + 1 ] = bnm.t2[ n ].t3[ m ].f[ k ];
				j = j + 2;
			}
		}
	}

	return true;
}

/******************************************************************************

  Check whether the given epoch of dfJD is too close to to one of the leap
  second marks. If so, return true.

  The given dfJD must be either in UTC or TAI

******************************************************************************/

bool cEOP::TooCloseToLeapSecondMark( double dfJD, bool bUTC )
{
	double dif;

	for( int i = 0; i < m_nNumberTAIUTC; i++ )
	{
		if( bUTC ) dif = dfJD - m_pstTAIUTC[ i ].dfJDUTC;
		else dif = dfJD - m_pstTAIUTC[ i ].dfJDTAI;

		if( fabs( dif ) * 86400.0 < 2.0 ) return true;	// yes, within 2 s of a leap second mark
	}

	return false;	// NO, it is more than 2 s from any leap second mark
}

/******************************************************************************

  GPS has a constant 19 s bias from TAI  i.e. TAI = GPS + 19 s;

  TAI has g_dfTTmTAIInSec = 32.184 s bias from ET (TT), i.e. TT = TAI + 32.184;


******************************************************************************/

bool cEOP::ConvertETGPS( double &dfIntSecET, double &dfFractionSecET,
					     double &dfIntSecGPS, double &dfFractionSecGPS, bool bET2GPS )
{
	if( bET2GPS )
	{
		double intTAISec = dfIntSecET - g_dfTTmTAIInSec, fraTAISec = dfFractionSecET;
		g_DateTimeZ.ReConstruct( intTAISec, fraTAISec );

		dfIntSecGPS = intTAISec - g_dfTAImGPSInSec;
		dfFractionSecGPS = fraTAISec;
	}
	else
	{
		double intTAISec = dfIntSecGPS + g_dfTAImGPSInSec, fraTAISec = dfFractionSecGPS;

		dfIntSecET = intTAISec + g_dfTTmTAIInSec;
		dfFractionSecET = fraTAISec;

		g_DateTimeZ.ReConstruct( dfIntSecET, dfFractionSecET );
	}

	return true;
}
